version: 2

.build_template: &build_definition
  steps:
    - checkout
    - run: bundle install --jobs=4 --retry=4 --path vendor/bundle
    - run:
        name: Run tests
        command: |
          bundle exec rspec
  working_directory: ~/app

jobs:
  build_ruby2_5:
    <<: *build_definition
    docker:
      - image: ruby:2.5
  build_ruby2_4:
    <<: *build_definition
    docker:
      - image: ruby:2.4
  build_ruby2_3:
    <<: *build_definition
    docker:
      - image: ruby:2.3
  build_ruby2_2:
    <<: *build_definition
    docker:
      - image: ruby:2.2

workflows:
  version: 2
  build_ruby_versions:
    jobs:
      - build_ruby2_5
      - build_ruby2_4
      - build_ruby2_3
      - build_ruby2_2
